#!/usr/bin/env bash

scp -r -i ~/.ssh/azure -o StrictHostKeyChecking=no shaefeli@shaefeliforaslvms1.westeurope.cloudapp.azure.com:~/memtier_benchmark-master/statFiles /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp6/2s1m

mv /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp6/2s1m/statFiles /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp6/2s1m/statsClient1

scp -r -i ~/.ssh/azure -o StrictHostKeyChecking=no shaefeli@shaefeliforaslvms2.westeurope.cloudapp.azure.com:~/memtier_benchmark-master/statFiles /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp6/2s1m

mv /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp6/2s1m/statFiles /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp6/2s1m/statsClient2

scp -r -i ~/.ssh/azure -o StrictHostKeyChecking=no shaefeli@shaefeliforaslvms3.westeurope.cloudapp.azure.com:~/memtier_benchmark-master/statFiles /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp6/2s1m

mv /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp6/2s1m/statFiles /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp6/2s1m/statsClient3

scp -r -i ~/.ssh/azure -o StrictHostKeyChecking=no shaefeli@shaefeliforaslvms4.westeurope.cloudapp.azure.com:~/code/stats /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp6/2s1m

mv /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp6/2s1m/stats /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp6/2s1m/statsMW1



