#!/usr/bin/env bash

scp -r -i ~/.ssh/azure -o StrictHostKeyChecking=no shaefeli@shaefeliforaslvms1.westeurope.cloudapp.azure.com:~/memtier_benchmark-master/statFiles /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp4

mv /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp4/statFiles /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp4/statsClient1

scp -r -i ~/.ssh/azure -o StrictHostKeyChecking=no shaefeli@shaefeliforaslvms2.westeurope.cloudapp.azure.com:~/memtier_benchmark-master/statFiles /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp4

mv /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp4/statFiles /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp4/statsClient2

scp -r -i ~/.ssh/azure -o StrictHostKeyChecking=no shaefeli@shaefeliforaslvms3.westeurope.cloudapp.azure.com:~/memtier_benchmark-master/statFiles /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp4

mv /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp4/statFiles /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp4/statsClient3

scp -r -i ~/.ssh/azure -o StrictHostKeyChecking=no shaefeli@shaefeliforaslvms4.westeurope.cloudapp.azure.com:~/code/stats /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp4

mv /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp4/stats /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp4/statsMW1

scp -r -i ~/.ssh/azure -o StrictHostKeyChecking=no shaefeli@shaefeliforaslvms5.westeurope.cloudapp.azure.com:~/code/stats /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp4

mv /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp4/stats /home/simon/Documents/ETH/asl/asl-fall17-project/collectedStatFiles/Exp4/statsMW2
