#!/usr/bin/env python
import numpy as np

statFile = open('client01inst1_ratio0:1.txt','r');
setThroughput = []
setLatency = []
setThroughputB = []
getThroughput = []
getLatency = []
getThroughputB = []
getHits=[]
getMisses=[]
totalThroughput = []
totalLatency = []
totalThroughputB = []
totalHits=[]
totalMisses=[]
for line in statFile:
	if "Sets" in line:
		words = line.split(" ")
		wordsF = [a for a in words if a!='']
		setThroughput.append(float(wordsF[1]));
		setLatency.append(float(wordsF[4]));
		setThroughputB.append(float(wordsF[5]));
	elif "Gets" in line:
		words = line.split(" ")
		wordsF = [a for a in words if a!='']
		getThroughput.append(float(wordsF[1]));
		getHits.append(float(wordsF[2]));
		getMisses.append(float(wordsF[3]));
		getLatency.append(float(wordsF[4]));
		getThroughputB.append(float(wordsF[5]));	
	elif "Totals" in line:
		words = line.split(" ")
		wordsF = [a for a in words if a!='']
		totalThroughput.append(float(wordsF[1]));
		totalHits.append(float(wordsF[2]));
		totalMisses.append(float(wordsF[3]));
		totalLatency.append(float(wordsF[4]));
		totalThroughputB.append(float(wordsF[5]));		
					
		
print(getThroughput)
print(getLatency)
print(getMisses)
