#!/usr/bin/env bash

testTime=$1
runTime=$((testTime+6))
perMWTime=$((runTime+2))

threads=(8 16 32 64)
shardedRead=("true")
#Note: all the rep=1 correspond to ratio 1:0 of client
ratios=(1 1 1 1 1 1)
repetitions=(1 2 3)
for rep in "${repetitions[@]}"
do
	for t in "${threads[@]}"
	do	
		for r in "${ratios[@]}"
		do
			timeout $runTime java -jar asl-fall17-project.jar -l 10.0.06 -p 6801 -t ${t} -s true -m 52.166.219.43:3000 52.166.219.179:3001 52.178.79.154:3002 &
			sleep $perMWTime 
		done
		mv statistics.txt stats/mw02_thread${t}_rep${rep}.txt
	
	done
done





