#!/usr/bin/env bash

testTime=$1
clients=(1 2 4 8 16 32)
threads=(2)
MWThread=(8 16 32 64)
#first write only then read only
ratios=("1:0")
repetitions=(1 2 3)
for r in "${repetitions[@]}"
do
	for mwt in "${MWThread[@]}"
	do
		for ra in "${ratios[@]}"
		do	
			for t in "${threads[@]}"
			do
				for s in "${clients[@]}"
				do
					memtier_benchmark --data-size=1024 --expiry-range=9999-10000 --key-maximum=10000 --clients=${s} --threads=${t} --port=6800 --protocol=memcache_text --test-time=$testTime --server=127.0.0.1 --hide-histogram --ratio=${ra} >>statFiles/client01inst1_MWT${mwt}_rep${r}.txt &
					memtier_benchmark --data-size=1024 --expiry-range=9999-10000 --key-maximum=10000 --clients=${s} --threads=${t} --port=6800 --protocol=memcache_text --test-time=$testTime --server=127.0.0.1 --hide-histogram --ratio=${ra} >>statFiles/client01inst2_MWT${mwt}_rep${r}.txt &
					sleep $((testTime+7)) 
				done
			done
		done
	done
done
