#!/usr/bin/env bash

testTime=$1
runTime=$((testTime+6))
perMWTime=$((runTime+2))

threads=(64)
shardedRead=("true" "false")
#We test for 4 different nr of keys
MGetSize=(1 1 1 1)
repetitions=(1 2 3)
for rep in "${repetitions[@]}"
do
	for s in "${shardedRead[@]}"
	do
		for t in "${threads[@]}"
		do	
			for r in "${MGetSize[@]}"
			do
				timeout $runTime java -jar asl-fall17-project.jar -l 10.0.0.7 -p 6800 -t ${t} -s ${s} -m 52.178.72.89:3000 52.178.76.230:3001 52.178.72.152:3002 &
				sleep $perMWTime 
			done
			mv statistics.txt stats/mw01_sharded${s}_rep${rep}.txt
	
		done
	done
done





