#!/usr/bin/env bash

./memtier_benchmark --data-size=1024 --expiry-range=9999-10000 --key-maximum=10000 --clients=20 --threads=2 --port=6800 --server=52.166.111.187 --protocol=memcache_text --test-time=300 ratio=1:0 &
./memtier_benchmark --data-size=1024 --expiry-range=9999-10000 --key-maximum=10000 --clients=20 --threads=2 --port=6801 --server=52.166.108.116 --protocol=memcache_text --test-time=300 ratio=1:0 &
sleep 305 

